from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict


class ShopPurchaseModel(BaseModel):
    owner_id: int
    product_mid: int
    limit_count: int
    total_count: int
    created_at: datetime
    updated_at: Optional[datetime]


class ShopListGetResponseModel(BaseModel):
    shop_purchase_list: list[ShopPurchaseModel]

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "shop_purchase_list": [
                        {
                            "owner_id": 288696,
                            "product_mid": 9,
                            "limit_count": 0,
                            "total_count": 6,
                            "created_at": "2019-09-15 03:32:54",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 88,
                            "limit_count": 0,
                            "total_count": 6,
                            "created_at": "2019-09-14 02:50:56",
                            "updated_at": "2021-09-27 17:45:01",
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 207,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-21 15:13:24",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 210,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-21 15:13:10",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 211,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-21 15:12:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1505,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-20 17:04:33",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1510,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-20 17:05:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1512,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-20 17:06:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1513,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-20 17:05:56",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1514,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-20 17:05:48",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1516,
                            "limit_count": 0,
                            "total_count": 3,
                            "created_at": "2019-08-20 17:06:18",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1520,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-08-27 03:40:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1539,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2019-08-28 17:37:12",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1593,
                            "limit_count": 0,
                            "total_count": 3,
                            "created_at": "2019-08-28 17:37:24",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1602,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-01 17:09:15",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1607,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-02 13:23:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1630,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:37:41",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1652,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:12:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1668,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:36:16",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1669,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:35:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1670,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:36:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1671,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:36:47",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1672,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:37:09",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1673,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-03 15:36:37",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1674,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2019-09-03 15:37:54",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1678,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-17 05:37:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1681,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-14 02:58:37",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1687,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-15 03:27:36",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1689,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2019-09-14 05:23:56",
                            "updated_at": "2019-09-15 02:59:54",
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1694,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-14 04:57:48",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1700,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-14 04:18:27",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1751,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-19 12:45:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1752,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-19 12:46:26",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1753,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-19 12:45:14",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 1757,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2019-09-19 12:45:32",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 2738,
                            "limit_count": 0,
                            "total_count": 31,
                            "created_at": "2022-08-18 19:30:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 3725,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-03-17 14:15:32",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 4358,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-03-25 04:58:52",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 4374,
                            "limit_count": 4,
                            "total_count": 4,
                            "created_at": "2020-03-25 04:59:28",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 4487,
                            "limit_count": 0,
                            "total_count": 6,
                            "created_at": "2020-03-21 04:19:58",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 4692,
                            "limit_count": 4,
                            "total_count": 4,
                            "created_at": "2020-04-23 05:48:09",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 4693,
                            "limit_count": 4,
                            "total_count": 4,
                            "created_at": "2020-04-23 05:48:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 5332,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-10-25 04:45:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 5578,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2020-06-17 12:04:45",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 5720,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-06-29 18:03:06",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 5726,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-06-29 18:03:39",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 5727,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-06-29 18:03:23",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 6860,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2020-08-18 18:33:12",
                            "updated_at": "2020-08-18 18:33:38",
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 8632,
                            "limit_count": 0,
                            "total_count": 3,
                            "created_at": "2020-11-14 00:56:13",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9579,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-14 16:43:38",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9644,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-16 11:37:51",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9645,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-16 11:38:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9646,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-16 11:38:51",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9647,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-16 11:38:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9648,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-16 11:38:16",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9651,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2020-12-16 11:39:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9800,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2020-12-24 07:12:13",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9804,
                            "limit_count": 3,
                            "total_count": 3,
                            "created_at": "2020-12-24 07:12:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9806,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2020-12-24 07:12:29",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9807,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2020-12-24 07:12:36",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 9810,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2020-12-24 07:12:59",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 12777,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-08 03:17:03",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13042,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:52",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13043,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13044,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13045,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:06",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13046,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:38",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13047,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13048,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:19",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13049,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:07:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13050,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13051,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:41",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13052,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:02",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13053,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13054,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:16",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13056,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:28",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13060,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13061,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:23",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13062,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:33",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13063,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:09",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13064,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:41",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13065,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:58",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13066,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:22",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13067,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:07:49",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13068,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:10",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13069,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:09:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13070,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:05",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13071,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:10:33",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13072,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 13074,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-04-07 04:08:31",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 14543,
                            "limit_count": 0,
                            "total_count": 6,
                            "created_at": "2022-04-22 05:04:03",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 16228,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2021-09-27 17:44:46",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 17675,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-09-27 17:44:25",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 17724,
                            "limit_count": 3,
                            "total_count": 3,
                            "created_at": "2021-09-28 02:59:08",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 17734,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2021-09-28 02:58:34",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 19913,
                            "limit_count": 0,
                            "total_count": 4,
                            "created_at": "2022-01-12 11:02:04",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 21178,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-01-12 11:02:59",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 24927,
                            "limit_count": 0,
                            "total_count": 1,
                            "created_at": "2022-08-08 08:21:35",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 24928,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-13 04:34:58",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 24929,
                            "limit_count": 20,
                            "total_count": 100,
                            "created_at": "2022-04-22 05:05:12",
                            "updated_at": "2022-09-10 18:11:00",
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 24965,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2022-04-22 05:00:18",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 24992,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-04-22 04:59:32",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 25117,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-04-22 04:59:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 25127,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-04-22 05:00:27",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 28911,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2022-08-08 08:21:08",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 28949,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-09 04:50:58",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 28982,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-09 04:49:57",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29019,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-09 04:50:28",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29150,
                            "limit_count": 0,
                            "total_count": 2,
                            "created_at": "2022-08-09 04:51:05",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29225,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-18 19:06:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29434,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-18 19:06:54",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29442,
                            "limit_count": 3,
                            "total_count": 3,
                            "created_at": "2022-08-18 19:07:13",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29443,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2022-08-18 19:07:19",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29461,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-08-25 07:45:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29673,
                            "limit_count": 0,
                            "total_count": 21,
                            "created_at": "2022-08-25 07:45:24",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29721,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-01 04:08:38",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29922,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-01 04:08:55",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29933,
                            "limit_count": 2,
                            "total_count": 2,
                            "created_at": "2022-09-01 04:09:05",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 29936,
                            "limit_count": 0,
                            "total_count": 24,
                            "created_at": "2022-09-01 04:09:13",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30246,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-16 04:10:31",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30452,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-16 04:11:14",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30455,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-16 04:11:34",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30466,
                            "limit_count": 6,
                            "total_count": 6,
                            "created_at": "2022-09-16 04:11:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30469,
                            "limit_count": 0,
                            "total_count": 3,
                            "created_at": "2022-09-16 04:11:52",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30481,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-22 05:32:12",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30496,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-22 05:32:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "product_mid": 30503,
                            "limit_count": 1,
                            "total_count": 1,
                            "created_at": "2022-09-22 05:32:27",
                            "updated_at": None,
                        },
                    ]
                }
            ],
        }
    )
