from pydantic import BaseModel
from pydantic import ConfigDict


class GachaInfoModel(BaseModel):
    gacha_mid: int
    now_step: int
    count_drew_gacha_free: int
    count_drew_gacha_discount: int
    gacha_drew_before: bool


class GachaRemainFreeCountModel(BaseModel):
    gacha_remain_free_count: int


class GachaRemainDiscountCountModel(BaseModel):
    gacha_remain_discount_count: int


class GachaListGetResponseModel(BaseModel):
    gacha_info_list: list[GachaInfoModel]
    gacha_remain_free_count: GachaRemainFreeCountModel
    gacha_remain_discount_count: GachaRemainDiscountCountModel

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "gacha_info_list": [
                        {
                            "gacha_mid": 1,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": True,
                        },
                        {
                            "gacha_mid": 3,
                            "now_step": 1,
                            "count_drew_gacha_free": 10,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": True,
                        },
                        {
                            "gacha_mid": 4,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 5,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 6,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 7,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": True,
                        },
                        {
                            "gacha_mid": 53,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 81,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 110,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 130,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 137,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 155,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 193,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 214,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 210,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 232,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 272,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 321,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 334,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 335,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 382,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 386,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 390,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 402,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 403,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 456,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 457,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 458,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 459,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 550,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 536,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 537,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 538,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 539,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 574,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 575,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 599,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 645,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 649,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 658,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 711,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 712,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 713,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 722,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 746,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 747,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 807,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 895,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 985,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 986,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 984,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1061,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1137,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1214,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1380,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1525,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1693,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1804,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 1920,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2022,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2210,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2393,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2587,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2753,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 2888,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3046,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3088,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3244,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3245,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3246,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3247,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3394,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3407,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3408,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3409,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3410,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3411,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3412,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3413,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3414,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3415,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3416,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3417,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3418,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3419,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3420,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3421,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3084,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3422,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3423,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3424,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3425,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3426,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3427,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3428,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3429,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3430,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3431,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3432,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                        {
                            "gacha_mid": 3433,
                            "now_step": 1,
                            "count_drew_gacha_free": 0,
                            "count_drew_gacha_discount": 0,
                            "gacha_drew_before": False,
                        },
                    ],
                    "gacha_remain_free_count": {"gacha_remain_free_count": 1},
                    "gacha_remain_discount_count": {"gacha_remain_discount_count": 6},
                }
            ],
        }
    )
