from enum import IntEnum


class ItemConsumeTypeEnum(IntEnum):
    GACHA_COUPON = 10
    GACHA_TICKET = 12
    HAIRSTYLE_OR_EXPRESSION = 29
    FP_REFILL_DRINK = 30
    LESSON_REFRESHMENT = 31
    POSE_CARD = 37
    UPGRADE_STONE_OR_MATERIAL = 39
    UNLOCK_STONE_OR_MATERIAL = 40
    GOOD_LUCK_BRINGING_OR_EPISODE_OR_GIRL_COIN = 48
    SPECIAL_FAN = 52
    DECO_PEN = 72
    HOT_SPRING_EFFECTIVENESS = 98
