from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict


class GirlPotentialModel(BaseModel):
    owner_id: int
    girl_mid: int
    skill_mid: int
    level: int
    polishing_count: int
    is_favorite: bool
    equipment_id: int
    pvp_equipment_id: int
    updated_at: Optional[datetime]
    created_at: datetime


class GirlPotentialGetResponseModel(BaseModel):
    girl_potential_list: list[GirlPotentialModel]

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "girl_potential_list": [
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-18 14:22:17",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-19 17:05:08",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-20 08:23:32",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-21 03:35:05",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-22 02:44:32",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 125,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-22 02:59:12",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-24 03:19:18",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-26 06:07:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-04-18 12:43:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-04-25 05:50:39",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 2,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-15 09:20:18",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 66107498,
                            "pvp_equipment_id": 66107498,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-08-02 05:45:20",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-08-27 03:41:09",
                            "created_at": "2019-08-02 14:43:03",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-01 01:31:46",
                            "created_at": "2019-08-18 16:14:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 66107498,
                            "pvp_equipment_id": 66107498,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-08-20 17:19:10",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 64002556,
                            "pvp_equipment_id": 64002556,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-08-20 17:51:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 62509126,
                            "pvp_equipment_id": 62509126,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-08-23 10:44:42",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2019-08-27 02:54:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-17 05:44:21",
                            "created_at": "2019-09-02 02:55:27",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 64002556,
                            "pvp_equipment_id": 64002556,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-06 12:09:35",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 220,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 62509126,
                            "pvp_equipment_id": 62509126,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-17 05:42:01",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-22 02:44:30",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 3,
                            "skill_mid": 125,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:38:59",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 121,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-22 02:57:41",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-07-29 10:14:32",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-05 16:18:03",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-15 09:20:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-16 08:31:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-18 05:33:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 119,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:39:09",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-26 16:11:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-27 13:05:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-01-02 12:53:02",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-01-16 02:59:01",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-02-14 14:10:54",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 4,
                            "skill_mid": 120,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-06 07:23:09",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 126,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-04-25 05:55:51",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 5,
                            "skill_mid": 125,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:36:07",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:36",
                            "created_at": "2019-08-31 04:14:02",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-14 04:26:08",
                            "created_at": "2019-09-01 16:22:29",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-12-11 05:45:26",
                            "created_at": "2019-09-01 16:45:12",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:46",
                            "created_at": "2019-09-02 02:47:42",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-12-11 05:45:27",
                            "created_at": "2019-09-02 13:21:54",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:46",
                            "created_at": "2019-09-03 15:40:02",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-14 04:26:57",
                            "created_at": "2019-09-06 03:42:24",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:36",
                            "created_at": "2019-09-14 04:40:23",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 220,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-08 03:14:01",
                            "created_at": "2019-09-14 05:33:56",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:36",
                            "created_at": "2019-09-14 05:52:07",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 118,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-08 03:14:00",
                            "created_at": "2019-12-05 09:04:33",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-08 03:14:01",
                            "created_at": "2019-12-05 09:32:52",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 123,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-07 03:49:12",
                            "created_at": "2020-03-22 02:56:34",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 6,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-08 03:14:01",
                            "created_at": "2020-04-25 05:54:33",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 123,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-22 03:00:00",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-03-23 03:13:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 254,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-17 11:56:49",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 118,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-10-25 04:56:35",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-11-14 00:59:48",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-01-12 07:20:40",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 7,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-08 03:24:59",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-19 05:16:24",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-22 17:30:48",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-24 02:52:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-25 02:07:19",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-09-24 03:19:12",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-10-22 08:38:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-10-25 04:43:14",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:23:32",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:35:24",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 121,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:38:47",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-22 08:43:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 8,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-05-07 19:34:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 568839669,
                            "pvp_equipment_id": 568839669,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 574314209,
                            "pvp_equipment_id": 574314209,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-08 03:19:13",
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 574314209,
                            "pvp_equipment_id": 574314209,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-06-15 19:29:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 118,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 274382667,
                            "pvp_equipment_id": 274382667,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-08-16 08:59:46",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 119,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 568839669,
                            "pvp_equipment_id": 568839669,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-12-11 05:35:34",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 9,
                            "skill_mid": 121,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:35:56",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-04-25 05:55:28",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-07-29 10:14:31",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-05 16:18:02",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-15 09:20:19",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-16 08:31:20",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-18 05:33:33",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-19 05:16:22",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-08-24 02:52:57",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-10-25 04:43:13",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:23:32",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 10,
                            "skill_mid": 120,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-06 07:22:23",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-05 05:19:18",
                            "created_at": "2019-08-02 05:53:43",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-05 05:19:15",
                            "created_at": "2019-08-05 01:48:14",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-02 13:23:28",
                            "created_at": "2019-08-18 16:14:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-05 05:19:15",
                            "created_at": "2019-08-20 09:16:34",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-05 05:19:17",
                            "created_at": "2019-08-20 17:52:07",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-05 05:19:18",
                            "created_at": "2019-08-27 02:54:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-01 16:57:13",
                            "created_at": "2019-08-30 13:17:17",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2019-09-08 12:49:43",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 70952660,
                            "pvp_equipment_id": 70952660,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-12-05 08:35:17",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 62505589,
                            "pvp_equipment_id": 62505589,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-03-22 02:56:03",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 274379570,
                            "pvp_equipment_id": 274379570,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-04-11 03:16:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 119,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:35:44",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 11,
                            "skill_mid": 118,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-06 07:22:51",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-15 03:48:52",
                            "created_at": "2019-09-05 18:14:25",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 70952498,
                            "pvp_equipment_id": 70952498,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-06 03:35:54",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-07 03:54:22",
                            "created_at": "2019-09-06 03:49:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 568839673,
                            "pvp_equipment_id": 568839673,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-06 04:07:37",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 69493354,
                            "pvp_equipment_id": 69493354,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-07 05:30:39",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 69493354,
                            "pvp_equipment_id": 69493354,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-07 05:33:30",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2019-09-14 04:25:42",
                            "created_at": "2019-09-14 03:42:34",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2020-03-22 02:52:28",
                            "created_at": "2019-09-14 05:14:34",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 220,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 70952498,
                            "pvp_equipment_id": 70952498,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-15 03:33:14",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 568839673,
                            "pvp_equipment_id": 568839673,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2019-09-15 03:47:48",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2021-04-07 03:53:39",
                            "created_at": "2019-12-05 09:33:21",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 12,
                            "skill_mid": 254,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-06-17 12:08:22",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-07 03:23:42",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-08 02:50:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-08 02:50:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-09 16:41:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-09 16:41:53",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-10 14:30:12",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-04-12 18:49:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-05-07 19:34:58",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-06-10 15:41:55",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 13,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-08-14 03:14:27",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-11-14 00:59:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-11-14 00:59:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-11-14 00:59:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 117,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:38:27",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-13 12:13:26",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-14 15:58:49",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-15 12:24:38",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-16 11:26:14",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-24 07:06:27",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-27 13:05:06",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 14,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2021-01-20 16:14:45",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 115,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2022-08-18 19:09:42",
                            "created_at": "2020-10-25 04:43:11",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 113,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2022-08-18 19:08:13",
                            "created_at": "2020-10-28 05:11:28",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 111,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-10-31 17:44:48",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 109,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 831114287,
                            "pvp_equipment_id": 831114287,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-11-08 04:10:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 107,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 1083195427,
                            "pvp_equipment_id": 1083195427,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-11-14 00:50:14",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 116,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-11-14 00:57:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 114,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-10 11:03:27",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 112,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:42:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 110,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": None,
                            "created_at": "2020-12-11 05:42:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 108,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 1083195427,
                            "pvp_equipment_id": 1083195427,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2020-12-11 05:42:36",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 269,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 0,
                            "pvp_equipment_id": 0,
                            "updated_at": "2022-08-18 19:08:13",
                            "created_at": "2020-12-16 11:46:05",
                        },
                        {
                            "owner_id": 288696,
                            "girl_mid": 16,
                            "skill_mid": 184,
                            "level": 1,
                            "polishing_count": 0,
                            "is_favorite": False,
                            "equipment_id": 568839676,
                            "pvp_equipment_id": 568839676,
                            "updated_at": "2023-03-22 19:15:47",
                            "created_at": "2021-04-07 04:05:01",
                        },
                    ]
                }
            ],
        }
    )
