from .bgm import BgmSchema as BgmSchema
from .bromide import BromideSchema as BromideSchema
from .casino_chip import CasinoChipSchema as CasinoChipSchema
from .casino_game import CasinoGameSchema as CasinoGameSchema
from .dishevelment_swimsuit import DishevelmentSwimsuitSchema as DishevelmentSwimsuitSchema
from .episode import EpisodeSchema as EpisodeSchema
from .friendly_value import FriendlyValueSchema as FriendlyValueSchema
from .friendship import FriendshipSchema as FriendshipSchema
from .furniture_myset import FurnitureMySetSchema as FurnitureMySetSchema
from .giftbox import GiftBoxSchema as GiftBoxSchema
from .girl import GirlSchema as GirlSchema
from .girl_equipment import GirlEquipmentSchema as GirlEquipmentSchema
from .girl_potential import GirlPotentialSchema as GirlPotentialSchema
from .honor import HonorSchema as HonorSchema
from .information import InformationSchema as InformationSchema
from .information_read import InformationReadSchema as InformationReadSchema
from .item_consume import ItemConsumeSchema as ItemConsumeSchema
from .item_equipemnt import ItemEquipmentSchema as ItemEquipmentSchema
from .item_furniture import ItemFurnitureSchema as ItemFurnitureSchema
from .item_seal import ItemSealSchema as ItemSealSchema
from .login_bonus import LoginBonusSchema as LoginBonusSchema
from .maintenance import MaintenanceSchema as MaintenanceSchema
from .max_combine_swimsuit import MaxCombineSwimsuitSchema as MaxCombineSwimsuitSchema
from .option_item_auto_lock import OptionItemAutoLockSchema as OptionItemAutoLockSchema
from .owner import OwnerSchema as OwnerSchema
from .owner_checked_at import OwnerCheckedAtSchema as OwnerCheckedAtSchema
from .owner_count_login import OwnerCountLoginSchema as OwnerCountLoginSchema
from .owner_room import OwnerRoomSchema as OwnerRoomSchema
from .photo_shoot import PhotoShootSchema as PhotoShootSchema
from .private_item import PrivateItemSchema as PrivateItemSchema
from .pvp_girl_equipment import PvpGirlEquipmentSchema as PvpGirlEquipmentSchema
from .pyon2_run import Pyon2RunSchema as Pyon2RunSchema
from .quest import QuestSchema as QuestSchema
from .request import RequestSchema as RequestSchema
from .request_log import RequestLogSchema as RequestLogSchema
from .seal_base import SealBaseSchema as SealBaseSchema
from .session import SessionSchema as SessionSchema
from .special_order import SpecialOrderSchema as SpecialOrderSchema
from .swimsuit_arrange_flag import SwimsuitArrangeFlagSchema as SwimsuitArrangeFlagSchema
from .tutorial import TutorialSchema as TutorialSchema
from .venus_board_girl_panel import VenusBoardGirlPanelSchema as VenusBoardGirlPanelSchema
from .venus_board_status import VenusBoardStatusSchema as VenusBoardStatusSchema
from .wallet import WalletSchema as WalletSchema
from .ywrk_skill import YwrkSkillSchema as YwrkSkillSchema
