from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict


class TutorialModel(BaseModel):
    owner_id: int
    event_mid: int
    flag: int
    created_at: datetime
    updated_at: Optional[datetime]


class TutorialResponseModel(BaseModel):
    tutorial_list: list[TutorialModel]

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "tutorial_list": [
                        {
                            "owner_id": 288696,
                            "event_mid": 0,
                            "flag": 1081080844,
                            "created_at": "2019-08-01 04:52:19",
                            "updated_at": "2024-07-17 05:58:48",
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 1,
                            "flag": 796884476,
                            "created_at": "2019-08-01 05:38:00",
                            "updated_at": "2020-10-31 18:10:28",
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 12,
                            "flag": 4,
                            "created_at": "2019-08-18 15:33:08",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 13,
                            "flag": 4,
                            "created_at": "2019-08-01 05:46:40",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 15,
                            "flag": 4,
                            "created_at": "2019-09-19 12:42:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 18,
                            "flag": 4,
                            "created_at": "2019-08-21 13:54:18",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 19,
                            "flag": 20,
                            "created_at": "2019-09-04 14:30:52",
                            "updated_at": "2019-09-14 02:50:08",
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 20,
                            "flag": 4,
                            "created_at": "2019-08-28 17:36:18",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 29,
                            "flag": 4,
                            "created_at": "2019-12-04 12:16:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 32,
                            "flag": 20,
                            "created_at": "2020-10-31 17:47:52",
                            "updated_at": "2020-11-08 04:15:40",
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 36,
                            "flag": 16,
                            "created_at": "2020-04-09 08:46:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 37,
                            "flag": 4,
                            "created_at": "2020-05-05 04:16:45",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 40,
                            "flag": 8,
                            "created_at": "2020-06-14 16:05:15",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 42,
                            "flag": 4,
                            "created_at": "2020-06-06 12:24:24",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 43,
                            "flag": 4,
                            "created_at": "2020-06-29 18:02:09",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 44,
                            "flag": 68,
                            "created_at": "2020-06-17 11:56:48",
                            "updated_at": "2020-06-17 11:56:50",
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 50,
                            "flag": 4,
                            "created_at": "2020-03-26 06:11:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 51,
                            "flag": 4,
                            "created_at": "2020-03-17 14:20:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 52,
                            "flag": 4,
                            "created_at": "2020-03-21 03:37:48",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 55,
                            "flag": 4,
                            "created_at": "2020-08-15 09:24:17",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 56,
                            "flag": 4,
                            "created_at": "2020-08-22 17:33:20",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 60,
                            "flag": 4,
                            "created_at": "2020-10-22 09:03:45",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 62,
                            "flag": 4,
                            "created_at": "2020-05-16 15:48:03",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 67,
                            "flag": 4,
                            "created_at": "2020-08-05 16:25:23",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 69,
                            "flag": 4,
                            "created_at": "2021-01-16 03:02:09",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 70,
                            "flag": 4,
                            "created_at": "2021-01-20 16:16:45",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 71,
                            "flag": 4,
                            "created_at": "2021-01-06 15:11:30",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 76,
                            "flag": 4,
                            "created_at": "2020-12-11 05:23:25",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 77,
                            "flag": 4,
                            "created_at": "2020-12-16 11:36:15",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 79,
                            "flag": 4,
                            "created_at": "2020-09-24 03:28:34",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 81,
                            "flag": 4,
                            "created_at": "2020-12-30 16:41:07",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 83,
                            "flag": 4,
                            "created_at": "2021-10-29 17:02:52",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 84,
                            "flag": 4,
                            "created_at": "2020-11-14 00:55:47",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 86,
                            "flag": 4,
                            "created_at": "2021-04-05 03:53:02",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 87,
                            "flag": 4,
                            "created_at": "2021-04-08 03:28:05",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 91,
                            "flag": 4,
                            "created_at": "2020-12-24 07:11:25",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 94,
                            "flag": 4,
                            "created_at": "2021-06-21 02:32:35",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 95,
                            "flag": 4,
                            "created_at": "2021-04-22 08:13:01",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 99,
                            "flag": 4,
                            "created_at": "2021-02-14 14:13:57",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 100,
                            "flag": 4,
                            "created_at": "2021-02-19 17:42:00",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 109,
                            "flag": 4,
                            "created_at": "2021-06-09 02:31:17",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 110,
                            "flag": 4,
                            "created_at": "2021-10-16 14:55:32",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 112,
                            "flag": 4,
                            "created_at": "2021-07-15 15:06:25",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 123,
                            "flag": 4,
                            "created_at": "2021-09-25 09:18:25",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 127,
                            "flag": 4,
                            "created_at": "2021-11-04 06:54:37",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 138,
                            "flag": 4,
                            "created_at": "2022-04-22 04:20:34",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 141,
                            "flag": 4,
                            "created_at": "2021-12-25 12:34:46",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 143,
                            "flag": 4,
                            "created_at": "2022-01-10 17:20:32",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 144,
                            "flag": 4,
                            "created_at": "2022-01-14 10:00:29",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 145,
                            "flag": 4,
                            "created_at": "2022-09-22 05:31:41",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 147,
                            "flag": 4,
                            "created_at": "2022-01-29 08:50:10",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 148,
                            "flag": 4,
                            "created_at": "2022-02-15 06:08:13",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 155,
                            "flag": 4,
                            "created_at": "2022-05-06 03:38:08",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 157,
                            "flag": 4,
                            "created_at": "2022-09-16 04:09:44",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 161,
                            "flag": 4,
                            "created_at": "2022-07-02 16:45:42",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 169,
                            "flag": 4,
                            "created_at": "2022-08-25 07:44:41",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 170,
                            "flag": 4,
                            "created_at": "2022-08-06 16:46:49",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 171,
                            "flag": 4,
                            "created_at": "2022-08-10 19:16:26",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 172,
                            "flag": 4,
                            "created_at": "2022-08-18 18:43:17",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 173,
                            "flag": 4,
                            "created_at": "2022-09-01 04:07:53",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 174,
                            "flag": 4,
                            "created_at": "2022-09-09 06:55:36",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 177,
                            "flag": 4,
                            "created_at": "2022-06-21 11:07:23",
                            "updated_at": None,
                        },
                        {
                            "owner_id": 288696,
                            "event_mid": 100000,
                            "flag": 462652,
                            "created_at": "2019-09-14 02:48:02",
                            "updated_at": "2024-07-17 06:08:55",
                        },
                    ]
                }
            ],
        }
    )
