from pydantic import Field

from ......base import NaaginBaseModel


class CsvFileModel(NaaginBaseModel):
    Beach_Flag_Data_csv: str = Field(alias="Beach_Flag_Data.csv")
    birthday_csv: str = Field(alias="birthday.csv")
    birthday_reward_csv: str = Field(alias="birthday_reward.csv")
    Blackjack_CharaParam_csv: str = Field(alias="Blackjack_CharaParam.csv")
    CasinoExchange_csv: str = Field(alias="CasinoExchange.csv")
    CasinoGoldChipInfo_csv: str = Field(alias="CasinoGoldChipInfo.csv")
    CasinoTop_csv: str = Field(alias="CasinoTop.csv")
    Consume_Parameter_csv: str = Field(alias="Consume_Parameter.csv")
    ConteList_csv: str = Field(alias="ConteList.csv")
    Costume_PullPoint_csv: str = Field(alias="Costume_PullPoint.csv")
    CR_Birthday_csv: str = Field(alias="CR_Birthday.csv")
    CR_FriendlyReward_csv: str = Field(alias="CR_FriendlyReward.csv")
    CR_FriendlyReward_Upgrade_csv: str = Field(alias="CR_FriendlyReward_Upgrade.csv")
    CR_FriendlyReward_Upgrade_Item_csv: str = Field(
        alias="CR_FriendlyReward_Upgrade_Item.csv"
    )
    CR_LevelupReward_csv: str = Field(alias="CR_LevelupReward.csv")
    CR_LevelupReward_Cmu_Table_csv: str = Field(alias="CR_LevelupReward_Cmu_Table.csv")
    CR_LevelupReward_Degree_Table_csv: str = Field(
        alias="CR_LevelupReward_Degree_Table.csv"
    )
    CR_LevelupReward_Item_Table_csv: str = Field(
        alias="CR_LevelupReward_Item_Table.csv"
    )
    CR_LevelupReward_Pose_Table_csv: str = Field(
        alias="CR_LevelupReward_Pose_Table.csv"
    )
    CR_Request_csv: str = Field(alias="CR_Request.csv")
    CR_Request_Challenge_Condition_csv: str = Field(
        alias="CR_Request_Challenge_Condition.csv"
    )
    CR_Request_Condition_csv: str = Field(alias="CR_Request_Condition.csv")
    CR_Request_Drop_csv: str = Field(alias="CR_Request_Drop.csv")
    CR_Request_Reward_Item_csv: str = Field(alias="CR_Request_Reward_Item.csv")
    CR_Request_Reward_Table_csv: str = Field(alias="CR_Request_Reward_Table.csv")
    CR_Request_Trend_csv: str = Field(alias="CR_Request_Trend.csv")
    CR_Request_Trend_Parameter_csv: str = Field(alias="CR_Request_Trend_Parameter.csv")
    Donketsu_Data_csv: str = Field(alias="Donketsu_Data.csv")
    EpisodeList_csv: str = Field(alias="EpisodeList.csv")
    EquipItemOffset_csv: str = Field(alias="EquipItemOffset.csv")
    Equipment_Parameter_csv: str = Field(alias="Equipment_Parameter.csv")
    Gacha_csv: str = Field(alias="Gacha.csv")
    GachaButtonPop_csv: str = Field(alias="GachaButtonPop.csv")
    GachaExternalCharacters_csv: str = Field(alias="GachaExternalCharacters.csv")
    GachaPopAndTexture_csv: str = Field(alias="GachaPopAndTexture.csv")
    GachaRewardItem_csv: str = Field(alias="GachaRewardItem.csv")
    GachaRewardTable_csv: str = Field(alias="GachaRewardTable.csv")
    GachaStepup_csv: str = Field(alias="GachaStepup.csv")
    GameParameters_csv: str = Field(alias="GameParameters.csv")
    giftbox_message_csv: str = Field(alias="giftbox_message.csv")
    girl_accessory_cost_table_csv: str = Field(alias="girl_accessory_cost_table.csv")
    Girl_Affection_Level_csv: str = Field(alias="Girl_Affection_Level.csv")
    Girl_Affectionup_Cmu_Table_csv: str = Field(alias="Girl_Affectionup_Cmu_Table.csv")
    Girl_Affectionup_Deg_Table_csv: str = Field(alias="Girl_Affectionup_Deg_Table.csv")
    Girl_Affectionup_Extra_Reward_csv: str = Field(
        alias="Girl_Affectionup_Extra_Reward.csv"
    )
    Girl_Affectionup_Item_Table_csv: str = Field(
        alias="Girl_Affectionup_Item_Table.csv"
    )
    Girl_Affectionup_Pose_Table_csv: str = Field(
        alias="Girl_Affectionup_Pose_Table.csv"
    )
    Girl_Affectionup_Reward_csv: str = Field(alias="Girl_Affectionup_Reward.csv")
    Girl_Affectionup_Voice_Table_csv: str = Field(
        alias="Girl_Affectionup_Voice_Table.csv"
    )
    girl_level_table_csv: str = Field(alias="girl_level_table.csv")
    Girl_Levelup_Cmu_Table_csv: str = Field(alias="Girl_Levelup_Cmu_Table.csv")
    Girl_Levelup_Degree_Table_csv: str = Field(alias="Girl_Levelup_Degree_Table.csv")
    Girl_Levelup_Item_Table_csv: str = Field(alias="Girl_Levelup_Item_Table.csv")
    Girl_Levelup_Pose_Table_csv: str = Field(alias="Girl_Levelup_Pose_Table.csv")
    Girl_Levelup_Reward_csv: str = Field(alias="Girl_Levelup_Reward.csv")
    girl_master_csv: str = Field(alias="girl_master.csv")
    girl_status_table_csv: str = Field(alias="girl_status_table.csv")
    GravurePanelData_csv: str = Field(alias="GravurePanelData.csv")
    GravurePanelRelease_csv: str = Field(alias="GravurePanelRelease.csv")
    Honor_csv: str = Field(alias="Honor.csv")
    Honor_Group_csv: str = Field(alias="Honor_Group.csv")
    Item_Addition_Accessary_Setting_csv: str = Field(
        alias="Item_Addition_Accessary_Setting.csv"
    )
    Item_Addition_Accessary_Table_csv: str = Field(
        alias="Item_Addition_Accessary_Table.csv"
    )
    Item_Decompose_Add_csv: str = Field(alias="Item_Decompose_Add.csv")
    Item_Decompose_Add_Group_csv: str = Field(alias="Item_Decompose_Add_Group.csv")
    Item_Decompose_Table_csv: str = Field(alias="Item_Decompose_Table.csv")
    Item_Ex_Cost_Table_csv: str = Field(alias="Item_Ex_Cost_Table.csv")
    Item_Level_Change_csv: str = Field(alias="Item_Level_Change.csv")
    Item_Level_Material_Table_csv: str = Field(alias="Item_Level_Material_Table.csv")
    Item_Level_Table_csv: str = Field(alias="Item_Level_Table.csv")
    Item_Level_Unlock_Table_csv: str = Field(alias="Item_Level_Unlock_Table.csv")
    Item_Photospot_Table_csv: str = Field(alias="Item_Photospot_Table.csv")
    Item_PoseGrowth_table_csv: str = Field(alias="Item_PoseGrowth_table.csv")
    Item_SkillGrowth_Group_csv: str = Field(alias="Item_SkillGrowth_Group.csv")
    Item_SkillGrowth_Table_csv: str = Field(alias="Item_SkillGrowth_Table.csv")
    Item_Status_Table_csv: str = Field(alias="Item_Status_Table.csv")
    Item_Upgrade_Cost_Table_csv: str = Field(alias="Item_Upgrade_Cost_Table.csv")
    Item_Upgrade_Exp_Table_csv: str = Field(alias="Item_Upgrade_Exp_Table.csv")
    Item_Upgrade_Table_csv: str = Field(alias="Item_Upgrade_Table.csv")
    KTAppExchange_csv: str = Field(alias="KTAppExchange.csv")
    LessonCampaign_csv: str = Field(alias="LessonCampaign.csv")
    LessonClearRank_csv: str = Field(alias="LessonClearRank.csv")
    LessonCoord_csv: str = Field(alias="LessonCoord.csv")
    LessonDrop_csv: str = Field(alias="LessonDrop.csv")
    LessonInfo_csv: str = Field(alias="LessonInfo.csv")
    LessonPotential_csv: str = Field(alias="LessonPotential.csv")
    LessonRewardItem_csv: str = Field(alias="LessonRewardItem.csv")
    LessonRewardTable_csv: str = Field(alias="LessonRewardTable.csv")
    LessonUnlock_csv: str = Field(alias="LessonUnlock.csv")
    LoginBonus_csv: str = Field(alias="LoginBonus.csv")
    LoginBonusDetail_csv: str = Field(alias="LoginBonusDetail.csv")
    LoginMessageMapping_csv: str = Field(alias="LoginMessageMapping.csv")
    LoginMonthlyTicketLink_csv: str = Field(alias="LoginMonthlyTicketLink.csv")
    MissionClearCondition_csv: str = Field(alias="MissionClearCondition.csv")
    MissionData_csv: str = Field(alias="MissionData.csv")
    MissionOpenCondition_csv: str = Field(alias="MissionOpenCondition.csv")
    MissionPanelData_csv: str = Field(alias="MissionPanelData.csv")
    MissionReward_csv: str = Field(alias="MissionReward.csv")
    MissionSpecialCondition_csv: str = Field(alias="MissionSpecialCondition.csv")
    NG_word_DMM_csv: str = Field(alias="NG_word_DMM.csv")
    NG_word_KT_csv: str = Field(alias="NG_word_KT.csv")
    NG_word_STEAM_csv: str = Field(alias="NG_word_STEAM.csv")
    OnsenDrop_csv: str = Field(alias="OnsenDrop.csv")
    OnsenGaugeItem_csv: str = Field(alias="OnsenGaugeItem.csv")
    OnsenQuality_csv: str = Field(alias="OnsenQuality.csv")
    OnsenRewardItem_csv: str = Field(alias="OnsenRewardItem.csv")
    OnsenRewardTable_csv: str = Field(alias="OnsenRewardTable.csv")
    owner_level_table_csv: str = Field(alias="owner_level_table.csv")
    owner_rank_csv: str = Field(alias="owner_rank.csv")
    owner_rank_bonus_csv: str = Field(alias="owner_rank_bonus.csv")
    owner_stamina_table_csv: str = Field(alias="owner_stamina_table.csv")
    OwnerReferralMissionData_csv: str = Field(alias="OwnerReferralMissionData.csv")
    PosecardPrice_csv: str = Field(alias="PosecardPrice.csv")
    PosecardShop_csv: str = Field(alias="PosecardShop.csv")
    PosecardShopItemDetail_csv: str = Field(alias="PosecardShopItemDetail.csv")
    PosecardShopItemDiscountLink_csv: str = Field(
        alias="PosecardShopItemDiscountLink.csv"
    )
    PosecardShopItemList_csv: str = Field(alias="PosecardShopItemList.csv")
    PosecardShopPointTypeLink_csv: str = Field(alias="PosecardShopPointTypeLink.csv")
    PosecardShopSaleInfo_csv: str = Field(alias="PosecardShopSaleInfo.csv")
    PresentBonus_csv: str = Field(alias="PresentBonus.csv")
    PresentDefiniteEx_csv: str = Field(alias="PresentDefiniteEx.csv")
    PresentDirectionRate_csv: str = Field(alias="PresentDirectionRate.csv")
    PresentDirectionRateEx_csv: str = Field(alias="PresentDirectionRateEx.csv")
    PresentGirlLimitedItem_csv: str = Field(alias="PresentGirlLimitedItem.csv")
    PresentReturn_csv: str = Field(alias="PresentReturn.csv")
    PresentReturnEx_csv: str = Field(alias="PresentReturnEx.csv")
    PresentReturnItem_csv: str = Field(alias="PresentReturnItem.csv")
    PresentReturnItemEx_csv: str = Field(alias="PresentReturnItemEx.csv")
    Price_csv: str = Field(alias="Price.csv")
    PyonPyon_Course_csv: str = Field(alias="PyonPyon_Course.csv")
    PyonPyon_Dice_csv: str = Field(alias="PyonPyon_Dice.csv")
    PyonPyon_RewardItem_csv: str = Field(alias="PyonPyon_RewardItem.csv")
    PyonPyon_Stage_csv: str = Field(alias="PyonPyon_Stage.csv")
    QuestAbleAutoChallengeCategory_csv: str = Field(
        alias="QuestAbleAutoChallengeCategory.csv"
    )
    QuestAbleAutoPlayCategory_csv: str = Field(alias="QuestAbleAutoPlayCategory.csv")
    QuestChallengeFesData_csv: str = Field(alias="QuestChallengeFesData.csv")
    QuestClearPrizeData_csv: str = Field(alias="QuestClearPrizeData.csv")
    QuestConditionData_csv: str = Field(alias="QuestConditionData.csv")
    QuestDailyLimitNumberData_csv: str = Field(alias="QuestDailyLimitNumberData.csv")
    QuestData_csv: str = Field(alias="QuestData.csv")
    QuestEnemyData_csv: str = Field(alias="QuestEnemyData.csv")
    QuestFesData_csv: str = Field(alias="QuestFesData.csv")
    QuestFirstClearPrizeData_csv: str = Field(alias="QuestFirstClearPrizeData.csv")
    QuestLicenseLevelData_csv: str = Field(alias="QuestLicenseLevelData.csv")
    QuestMatchData_csv: str = Field(alias="QuestMatchData.csv")
    QuestMatchingOwnerRankPrize_csv: str = Field(
        alias="QuestMatchingOwnerRankPrize.csv"
    )
    QuestRankBorderData_csv: str = Field(alias="QuestRankBorderData.csv")
    QuestSRankClearPrizeData_csv: str = Field(alias="QuestSRankClearPrizeData.csv")
    Ranking_csv: str = Field(alias="Ranking.csv")
    RankingBeachFlag_csv: str = Field(alias="RankingBeachFlag.csv")
    RankingDonketsu_csv: str = Field(alias="RankingDonketsu.csv")
    RankingFes_csv: str = Field(alias="RankingFes.csv")
    RankingIDToItemID_csv: str = Field(alias="RankingIDToItemID.csv")
    RankingItem_csv: str = Field(alias="RankingItem.csv")
    RankingPointReward_csv: str = Field(alias="RankingPointReward.csv")
    RankingRaidReward_csv: str = Field(alias="RankingRaidReward.csv")
    RankingReward_csv: str = Field(alias="RankingReward.csv")
    RockClimbingLongData_csv: str = Field(alias="RockClimbingLongData.csv")
    RockClimbingShortData_csv: str = Field(alias="RockClimbingShortData.csv")
    Roulette_BetIndexData_csv: str = Field(alias="Roulette_BetIndexData.csv")
    Roulette_BetTypeToOdds_csv: str = Field(alias="Roulette_BetTypeToOdds.csv")
    SealBase_csv: str = Field(alias="SealBase.csv")
    SealExpItem_csv: str = Field(alias="SealExpItem.csv")
    SealSetting_csv: str = Field(alias="SealSetting.csv")
    SealSkillCorrect_csv: str = Field(alias="SealSkillCorrect.csv")
    SealUpgrade_csv: str = Field(alias="SealUpgrade.csv")
    Shop_csv: str = Field(alias="Shop.csv")
    ShopCategory_csv: str = Field(alias="ShopCategory.csv")
    ShopItemDetail_csv: str = Field(alias="ShopItemDetail.csv")
    ShopItemDiscountLink_csv: str = Field(alias="ShopItemDiscountLink.csv")
    ShopItemList_csv: str = Field(alias="ShopItemList.csv")
    ShopPointTypeLink_csv: str = Field(alias="ShopPointTypeLink.csv")
    ShopSaleInfo_csv: str = Field(alias="ShopSaleInfo.csv")
    skill_csv: str = Field(alias="skill.csv")
    skill_char_csv: str = Field(alias="skill_char.csv")
    skill_efct_growth_csv: str = Field(alias="skill_efct_growth.csv")
    skill_polishing_exp_item_csv: str = Field(alias="skill_polishing_exp_item.csv")
    skill_polishing_exp_table_csv: str = Field(alias="skill_polishing_exp_table.csv")
    skill_polishing_pp_growth_csv: str = Field(alias="skill_polishing_pp_growth.csv")
    skill_rock_climbing_efct_growth_csv: str = Field(
        alias="skill_rock_climbing_efct_growth.csv"
    )
    skill_rock_climbing_exp_csv: str = Field(alias="skill_rock_climbing_exp.csv")
    skill_rock_climbing_pp_growth_csv: str = Field(
        alias="skill_rock_climbing_pp_growth.csv"
    )
    skill_rock_climbing_trig_growth_csv: str = Field(
        alias="skill_rock_climbing_trig_growth.csv"
    )
    skill_trig_growth_csv: str = Field(alias="skill_trig_growth.csv")
    subscription_csv: str = Field(alias="subscription.csv")
    subscription_details_csv: str = Field(alias="subscription_details.csv")
    TrendBonus_csv: str = Field(alias="TrendBonus.csv")
    TrendEventFes_csv: str = Field(alias="TrendEventFes.csv")
    TrendFesList_csv: str = Field(alias="TrendFesList.csv")
    TrendKizunaIdList_csv: str = Field(alias="TrendKizunaIdList.csv")
    TrendMainFes_csv: str = Field(alias="TrendMainFes.csv")
    TrendPresentIdList_csv: str = Field(alias="TrendPresentIdList.csv")
    TrendPresentSupportGroupIdList_csv: str = Field(
        alias="TrendPresentSupportGroupIdList.csv"
    )
    TrendPvpSeasonalBonus_csv: str = Field(alias="TrendPvpSeasonalBonus.csv")
    VenusBoard_KPIPanelType_csv: str = Field(alias="VenusBoard_KPIPanelType.csv")
    VenusBoard_Link_csv: str = Field(alias="VenusBoard_Link.csv")
    VenusBoard_Map_csv: str = Field(alias="VenusBoard_Map.csv")
    VenusBoard_Panel_csv: str = Field(alias="VenusBoard_Panel.csv")
    VenusBoard_PanelCondition_csv: str = Field(alias="VenusBoard_PanelCondition.csv")
    VenusBoard_PanelReward_csv: str = Field(alias="VenusBoard_PanelReward.csv")
    VenusBoard_ReleaseGirls_csv: str = Field(alias="VenusBoard_ReleaseGirls.csv")
    version_info_csv: str = Field(alias="version_info.csv")
    voting_csv: str = Field(alias="voting.csv")
    voting_candidate_csv: str = Field(alias="voting_candidate.csv")
    YwrkSkillTable_csv: str = Field(alias="YwrkSkillTable.csv")
    file_encrypt_key: str


class CsvListGetResponseModel(NaaginBaseModel):
    csv_file_list: CsvFileModel
